In [16]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import eig
from numpy.linalg import eigh

a = np.array([[-4, -3, -3],
              [0, -1, 0],
              [6, 6, 5]])

a_inv = inv(a)
a_eig = eig(a)

In [12]:
a_inv

array([[-2.5, -1.5, -1.5],
       [-0. , -1. , -0. ],
       [ 3. ,  3. ,  2. ]])

In [13]:
a_eig[0]

array([-1.,  2., -1.])

In [14]:
a_eig[1]

array([[-0.70710678,  0.4472136 , -0.40824829],
       [ 0.        ,  0.        ,  0.81649658],
       [ 0.70710678, -0.89442719, -0.40824829]])

In [17]:
a_eigh = eigh(a)

In [19]:
a_eigh

(array([-8.30099389, -2.27757628, 10.57857017]),
 array([[-0.73306142,  0.58721586, -0.34321785],
        [-0.43184431, -0.7916823 , -0.43214537],
        [ 0.52548211,  0.16857242, -0.83393758]]))