In [8]:
import numpy as np
from fractions import Fraction
# fraction format output
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

**特征值和特征向量**

In [9]:
A = np.array([
    [-1, 1, 0],
    [-4, 3, 0],
    [1, 0, 2]
])

eigen_value, eigen_vector = np.linalg.eig(A)
print("eigen value:", eigen_value)
print("eigen vector", eigen_vector)

eigen value: [2 1 1]
eigen vector [[0 192060/470449 192060/470449]
 [0 384120/470449 384120/470449]
 [1 -192060/470449 -192060/470449]]


**对角化**

In [10]:
# A = P*B*P^{-1}
from sympy import *
A = Matrix([
    [2, 0, 0],
    [0, 0.5, 1],
    [0, 0, 0.5]
])

P, B = A.diagonalize()
print("P: ", P)
print("diag B: ", B)

P:  Matrix([[1.00000000000000, 0, 0], [0, 1.00000000000000, -1.00000000000000], [0, 0, 1.51929083932157e-64]])
diag B:  Matrix([[2.00000000000000, 0, 0], [0, 0.500000000000000, 0], [0, 0, 0.500000000000000]])


**Jordan 标准型**

In [11]:
A = np.array([
    [5, 4, 2, 1],
    [0, 1, -1, -1],
    [-1, -1, 3, 0],
    [1, 1, -1, 2]
])

m = Matrix(A)

P, J = m.jordan_form()

print(P)
print(J)

Matrix([[-1, 1, 1, 1], [1, -1, 0, 0], [0, 0, -1, 0], [0, 1, 1, 0]])
Matrix([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 4, 1], [0, 0, 0, 4]])


**SVD 奇异值分解**

In [12]:
A = np.array([
    [5, 4, 2, 1],
    [0, 1, -1, -1],
    [-1, -1, 3, 0],
    [1, 1, -1, 2]
])

np.linalg.svd(A)

(array([[-253855/262273, 193320/999931, 4921/34765, 25135/331523],
        [-25612/825273, -65323/219315, 123157/207208, -573786/768779],
        [32899/297245, 525551/612485, -152783/950600, -217841/458592],
        [-218567/977957, -317454/855691, -403917/521080, -401156/872175]]),
 array([1930449/277330, 1407176/377783, 1922646/925055, 289361/487292]),
 array([[-613445/825347, -362419/595432, -129413/667652, -80453/404681],
        [-70422/999701, -155243/767350, 735421/754695, -25570/379761],
        [8763/195166, 140837/535980, -8783/998732, -946171/981735],
        [514447/775038, -337873/468748, -94751/838249, -139873/849956]]))

**QR 分解**